version: '3'

services:
  db:
    container_name: email_db
    image: postgres:12
    restart: always
    env_file:
      - .env.production
    ports:
      - 5434:5432
    volumes:
      - pgdata:/var/lib/postgresql/data


volumes:
  pgdata: